version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://wdc_user:your_secure_password@db:5432/working_days_db
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: registry.redhat.io/rhel8/postgresql-13:1-215
    environment:
      - POSTGRESQL_USER=wdc_user
      - POSTGRESQL_PASSWORD=your_secure_password
      - POSTGRESQL_DATABASE=working_days_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wdc_user -d working_days_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: